config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
    resources :users do 
      member do
        get :following, :followers
      end
    end
    resources :relationships,       only: [:create, :destroy]




 
    resources :tests do
      resources :likes, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end
    root 'tests#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :test
  belongs_to :user
  validates_uniqueness_of :test_id, scope: :user_id
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :following, class_name: "User"
    validates :follower_id, presence: true
    validates :following_id, presence: true
end

app/models/test.rb
class Test < ApplicationRecord
    mount_uploader :image, ImageUploader

    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
    has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :tests, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :liked_tests, through: :likes, source: :test
  has_many :comments, dependent: :destroy
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  has_many :followings, through: :following_relationships
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships
  mount_uploader :image, ImageUploader
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end  

  def already_liked?(test)
    self.likes.exists?(test_id: test.id)
  end
  validates :name, presence: true 
  validates :profile, length: { maximum: 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
    def configure_permitted_parameters
      
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      
      devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :authenticate_user!

    def create
      test = Test.find(params[:test_id])
      comment = test.comments.build(comment_params) 
      comment.user_id = current_user.id
      if comment.save
        flash[:success] = "コメントしました"
        redirect_back(fallback_location: root_path)
      else
        flash[:success] = "コメントできませんでした"
        redirect_back(fallback_location: root_path)
      end
    end

    def destroy
      comment = Comment.find_by(test_id: params[:test_id], user_id: current_user.id)
      comment.destroy
      redirect_back(fallback_location: root_path)
     
        
    end

    
  
    private
    def comment_params
      params.require(:comment).permit(:content)
    end
    
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(test_id: params[:test_id]) 
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(test_id: params[:test_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
   
    def create
        @user = User.find(params[:relationship][:following_id])
        current_user.follow!(@user)
        redirect_to @user
    end

    def destroy
        @user = Relationship.find(params[:id]).following
        current_user.unfollow!(@user)
        redirect_to @user
    end
    
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  before_action :authenticate_user!  
    def index
        @tests =Test.all

      if params[:search] != nil && params[:search] !=''
        @tests = Test.where("body LIKE ? ",'%' + params[:search] + '%')
      else
        @tests =Test.all
      end
    end

    def new
        @test = Test.new
    end

    def create
        test = Test.new(test_params)

        test.user_id = current_user.id
        if test.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

    def show
      @test = Test.find(params[:id])
      @comments = @test.comments
      @comment = Comment.new
    end

    def edit
      @test = Test.find(params[:id])
    end

    def update
      test = Test.find(params[:id])
      if test.update(test_params)
        redirect_to :action => "show", :id => test.id
      else
        redirect_to :action => "new"
      end
    end

    def destroy
      test = Test.find(params[:id])
      test.destroy
      redirect_to action: :index
    end

    private
    def test_params
      params.require(:test).permit(:body, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
        @user = User.find(params[:id]) 
    end

    def following
        @user  = User.find(params[:id])
        @users = @user.followings
        render 'show_follow'
    end
  
    def followers
      @user  = User.find(params[:id])
      @users = @user.followers
      render 'show_follower'
    end

    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def current_user?(user)
        user == current_user
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geekinstagram</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@497;700&family=Pushster&display=swap" rel="stylesheet">
  </head>

  <body>
    <header>
    <h1 class="geek">GeekInstagram</h1>
    <%= link_to "ログイン", root_path %>
    <%= link_to "新規登録", new_user_registration_path %>
    <%= link_to 'ログアウト', destroy_user_session_path, method: :delete %>

      <% if user_signed_in? %>
      <%= link_to "マイページ", user_path(current_user.id) %>
      <% end %>

    
    <%= link_to "投稿一覧", tests_path %>
    

    <%= link_to "新規投稿", new_test_path %>
    
    
    

    
    
    </header>
      <main>
      <%= yield %>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
      </main>
    
      
  </body>
</html>

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
    <div><%= f.hidden_field :following_id %></div>
    <%= f.submit "Follow", class: "btn btn-large btn-primary follow-btn" %>
  <% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
<div id="follow_form">
<% if current_user.following?(@user) %>
  <%= render 'unfollow' %>
<% else %>
  <%= render 'follow' %>
<% end %>
</div>
<% end %>  

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.followings.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(following_id: @user.id), html: { method: :delete }) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-large follow-btn" %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>マイページ</h1>
<p>名前 : <%= @user.name %></p>

<% if @user.image? %>                                                              
<%= image_tag @user.image.url, class: "rounded-circle", size: "150x150" %>
<% else %>
<%= image_tag "16_2_302.png", class: "rounded-circle", size: "150x150" %>
<% end %>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>
<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>
<%= render 'follow_form' %>
<%= render 'stats' %>

<h2 class="m-3">ユーザーの投稿一覧</h2>
  <div class="contaner ml-5">
    <div class="row">
      <% @user.tests.each do |t| %>
          <p class="card m-2"><%= image_tag t.image_url, size: "250x200" if t.image? %>
          <%= link_to "詳細へ", test_path(t.id) %></p>
      <% end %>
    </div>
  </div>



<%= link_to "投稿一覧に戻る", tests_path %>

app/views/users/show_follow.html.erb
<p> フォローリスト</p>
<% @user.followings.each do |user| %>
   
    <table>
    <tr>
      <td>  <%= user.name %> </td>
      <td><%= link_to '詳細', user_path(user) %></td>
    </tr>
    
    </table>
    <% end %>

app/views/users/show_follower.html.erb
<p>フォロワーリスト</p>
<% @user.followers.each do |user| %>
   
    <table>
    <tr>
      <td>  <%= user.name %> </td>
      <td><%= link_to '詳細', user_path(user) %></td>
    </tr>
    
    </table>
    <% end %>